### ISSUE TITLE
Good Practiceのページの最新版追従

### ISSUE THREAD

**Issue by nyampire** [osmfj/osm_japan_issues#6]
Good Practiceのページの翻訳を最新版に追従させたい

http://wiki.openstreetmap.org/wiki/Good_practice
http://wiki.openstreetmap.org/wiki/JA:%E3%82%B0%E3%83%83%E3%83%89%E3%83%97%E3%83%A9%E3%82%AF%E3%83%86%E3%82%A3%E3%82%B9

**Comment by nyampire** [comment]
初心者ガイドなど、もっとわかりやすい場所からリンク貼りたい。

**Comment by tankaru** [comment]
どのあたりが古い内容になっていますか？
具体的な場所が分かれば手を入れますが。

**Comment by nyampire** [comment]
失礼しました、12月25日付けで追従してるみたいですね。
いちどCloseして、「osm.jpからリンクを貼る」という別Issueに切り替えます。
- [JA:グッドプラクティス](https://wiki.openstreetmap.org/w/index.php?title=JA:%E3%82%B0%E3%83%83%E3%83%89%E3%83%97%E3%83%A9%E3%82%AF%E3%83%86%E3%82%A3%E3%82%B9&action=history)
- [Good Practice](https://wiki.openstreetmap.org/w/index.php?title=Good_practice&action=history)
