### ISSUE TITLE
weeklyosmの翻訳追従

### ISSUE THREAD

**Issue by nyampire** [osmfj/osm_japan_issues#7]
毎週公開される[weeklyosm](http://www.weeklyosm.eu/ja/)の記事翻訳を行うためのリソースが、現在 @nyampire ひとりで、まわっていない。

**Comment by tankaru** [comment]
翻訳能力に自信はありませんが、参加できます。どのような形で参加することが可能でしょうか？

**Comment by KMR-zoar** [comment]
[WeeklyOSM](https://wiki.openstreetmap.org/wiki/WeeklyOSM) の [Want to join us?](https://wiki.openstreetmap.org/wiki/WeeklyOSM#Want_to_join_us.3F) に書かれているメールアドレスかブログに参加したい旨連絡すると、 OSM のアカウントで翻訳システムの OSMBC にログインできるようにセットしてくれます。  
というか本日やってもらいました。  
他にも参加方法あるかもしれませんが…

同じく翻訳能力に自信ありませんので興味ある方はよろしくお願いします。

**Comment by tankaru** [comment]
ありがとうございます。ブログからコンタクトしてみました。

**Comment by nyampire** [comment]
参加ありがとうございます！
マニュアルはこちらですが、正直、僕も説明できるほど使いこなしていません。。
基本的には、Openしているものや、Need Reviewのものをひとつずつこなしてゆく作業になります。

http://thefive.sabic.uberspace.de/blog/305/preview?lang=EN

チームとはSlackでやりとりしていますので、そちらに画像はるなどして説明を求めるのが早いです。
なお、チームのノリは激軽です :)

**Comment by nyampire** [comment]
チームメンバーの募集について別Issueを立ち上げる。

いったんここはCloseする
